#!/bin/bash
if [[ "$1" == "--amend" && "$2" == "--no-edit" ]]; then
    exit 0
fi
commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")
if ! echo "$commit_msg" | grep -E -q "^(bugfix:|release:|feat:|config:|chore:)"; then
    echo "Error: Wrong prefix in commit message ❗❗❗"
    echo "Allowed prefixes: bugfix: | release: | feat: | config:"
    exit 1
fi
